Repository xlsynth/bedrock-rtl, pull requests merged in 2024-11, with the labels that each got.

#149 Improve `BR_ASSERT_STATIC` for better logging
  macros/br_asserts.svh
Labels: enhancement

#153 Fix reset bug in `br_delay_valid`
  delay/rtl/br_delay_valid.sv
Labels: bug

#164 Use `BR_ASSERT_COMB_IMPL` in delay modules
  delay/fpv/br_delay/BUILD.bazel
  delay/rtl/br_delay.sv
  delay/rtl/br_delay_nr.sv
  delay/rtl/br_delay_valid.sv
  delay/rtl/br_delay_valid_next.sv
  delay/rtl/br_delay_valid_next_nr.sv
Labels: bug

#165 Fixes to coding style in demuxes to make simulator happier
  demux/rtl/br_demux_bin.sv
  demux/rtl/br_demux_onehot.sv
Labels: bug

#166 Fix address decoder bugs
  ram/rtl/br_ram_addr_decoder.sv
Labels: bug

#167 Assertion fixes in br_demux_onehot
  demux/rtl/br_demux_bin.sv
  demux/rtl/br_demux_onehot.sv
Labels: bug

#168 Fix latency asserts in `br_ram_flops_1r1w`
  ram/rtl/br_ram_flops_1r1w.sv
Labels: bug

#152 Simulation unit test for `br_ram_flops_1r1w`
  ram/sim/BUILD.bazel
  ram/sim/br_ram_flops_1r1w_tb.sv
Labels: enhancement

#169 Fix lint issues in `br_ram_addr_decoder`
  ram/rtl/BUILD.bazel
  ram/rtl/br_ram_addr_decoder.sv
Labels: bug

#140 Add support for non-zero read latency to FIFO controllers
  delay/rtl/br_delay_valid.sv
  fifo/rtl/BUILD.bazel
  fifo/rtl/br_fifo_ctrl_1r1w.sv
  fifo/rtl/br_fifo_ctrl_1r1w_push_credit.sv
  fifo/rtl/br_fifo_flops.sv
  fifo/rtl/br_fifo_flops_push_credit.sv
  fifo/rtl/internal/BUILD.bazel
  fifo/rtl/internal/br_fifo_pop_ctrl.sv
  fifo/rtl/internal/br_fifo_push_ctrl.sv
  fifo/rtl/internal/br_fifo_push_ctrl_credit.sv
  fifo/rtl/internal/br_fifo_staging_buffer.sv
  fifo/sim/BUILD.bazel
  fifo/sim/br_fifo_flops_tb.sv
  fifo/sim/br_fifo_test_harness.sv
Labels: enhancement

#174 Clarify `BR_ENABLE_ASSERT_COMB`
  README.adoc
Labels: documentation

#178 Enable `BR_ASSERT_STATIC` unconditionally; canonicalize fail strings
  macros/br_asserts.svh
Labels: bug

#188 Update parity codes in readme
  README.adoc
Labels: documentation

#179 Some bug fixes and refactors for FIFOs
  fifo/rtl/br_fifo_flops_push_credit.sv
  fifo/rtl/internal/BUILD.bazel
  fifo/rtl/internal/br_fifo_pop_ctrl.sv
  fifo/rtl/internal/br_fifo_pop_ctrl_core.sv
  fifo/rtl/internal/br_fifo_push_ctrl.sv
  fifo/rtl/internal/br_fifo_push_ctrl_core.sv
  fifo/rtl/internal/br_fifo_push_ctrl_credit.sv
  fifo/sim/BUILD.bazel
Labels: bug

#196 `custom_tcl_header`, `custom_tcl_body` for all rules
  arb/fpv/BUILD.bazel
  bazel/verilog.bzl
Labels: enhancement

#197 Fix VCS lint escape in br_counter.sv
  counter/rtl/br_counter.sv
Labels: bug

#198 Update bazel docs
  bazel/verilog_rules.md
Labels: documentation

#199 Fix runfiles handling bug
  bazel/verilog.bzl
Labels: bug

#205 Patch `verilog_library` so that more file extensions are allowed
  dependency_support/rules_hdl/extension.bzl
  dependency_support/rules_hdl/verilog/providers.bzl.patch
Labels: enhancement

#180 Add single-bit CDC synchronizer
  cdc/rtl/BUILD.bazel
  cdc/rtl/br_cdc_bit_toggle.sv
  gate/rtl/BUILD.bazel
  gate/rtl/br_gate_behav.sv
Labels: enhancement

#183 Implement CDC FIFOs
  cdc/rtl/BUILD.bazel
  cdc/rtl/br_cdc_fifo_ctrl_1r1w.sv
  cdc/rtl/br_cdc_fifo_ctrl_1r1w_push_credit.sv
  cdc/rtl/br_cdc_fifo_flops.sv
  cdc/rtl/br_cdc_fifo_flops_push_credit.sv
  cdc/rtl/internal/BUILD.bazel
  cdc/rtl/internal/br_cdc_fifo_gray_count_sync.sv
  cdc/rtl/internal/br_cdc_fifo_pop_ctrl.sv
  cdc/rtl/internal/br_cdc_fifo_pop_flag_mgr.sv
  cdc/rtl/internal/br_cdc_fifo_push_ctrl.sv
  cdc/rtl/internal/br_cdc_fifo_push_ctrl_credit.sv
  cdc/rtl/internal/br_cdc_fifo_push_flag_mgr.sv
  cdc/sim/BUILD.bazel
  cdc/sim/br_cdc_fifo_flops_tb.sv
  fifo/rtl/internal/BUILD.bazel
  fifo/sim/br_fifo_test_harness.sv
Labels: enhancement

#208 ECC bonanza! `eccgen.py`, `br_ecc_secded_encoder`, `br_ecc_secded_decoder`, `br_enc_countones`, and basic unit tests
  BUILD.bazel
  MODULE.bazel
  README.adoc
  ecc/rtl/BUILD.bazel
  ecc/rtl/br_ecc_secded_decoder.sv
  ecc/rtl/br_ecc_secded_encoder.sv
  ecc/scripts/BUILD.bazel
  ecc/scripts/br_ecc_secded_decoder.sv.jinja2
  ecc/scripts/br_ecc_secded_encoder.sv.jinja2
  ecc/scripts/eccgen.py
  ecc/scripts/hsiao_secded.py
  ecc/scripts/hsiao_secded_test.py
  ecc/sim/BUILD.bazel
  ecc/sim/br_ecc_secded_encoder_decoder_tb.sv
  enc/rtl/BUILD.bazel
  enc/rtl/br_enc_countones.sv
  requirements.in
  requirements_lock_3_12.txt
Labels: enhancement

#224 Upstream `verilog_runner.py` with `VERILOG_RUNNER_PLUGIN_PATH` var
  .gitignore
  bazel/BUILD.bazel
  bazel/verilog.bzl
  bazel/verilog_rules.md
  bazel/write_placeholder_verilog_runner_py.bzl
  python/verilog_runner/BUILD.bazel
  python/verilog_runner/README.adoc
  python/verilog_runner/cli.py
  python/verilog_runner/eda_tool.py
  python/verilog_runner/plugins.py
  python/verilog_runner/util.py
  python/verilog_runner/util_test.py
  python/verilog_runner/verilog_runner.py
  requirements.in
Labels: enhancement

#228 Plugin API version: 1.0
  python/verilog_runner/plugins.py
Labels: enhancement

#229 Update README for the plugins
  README.adoc
Labels: documentation
