Repository xlsynth/bedrock-rtl, pull requests merged in 2024-12, with the labels that each got.

#236 Uniquify ram mock filename
  ram/rtl/BUILD.bazel
  ram/rtl/br_ram_flops_1r1w_mock.sv
  ram/rtl/mock/BUILD.bazel
  ram/sim/BUILD.bazel
  ram/sim/br_ram_flops_1r1w_tb.sv
Labels: bug

#240 Emulation-friendly flop-RAM coding style
  ram/rtl/br_ram_flops_1r1w_mock.sv
  ram/rtl/br_ram_flops_1r1w_tile.sv
Labels: bug

#253 Update ECC lib and Bazel verilog rules documentation
  bazel/verilog_rules.md
  ecc/rtl/br_ecc_secded_decoder.sv
  ecc/rtl/br_ecc_secded_encoder.sv
  ecc/rtl/br_ecc_sed_decoder.sv
  ecc/rtl/br_ecc_sed_encoder.sv
  python/eccgen/br_ecc_secded_decoder.sv.jinja2
  python/eccgen/br_ecc_secded_encoder.sv.jinja2
Labels: documentation

#248 Fix single entry FIFO staging buffer
  fifo/rtl/internal/br_fifo_staging_buffer.sv
Labels: bug

#251 Add freelist manager module and unit test
  tracker/rtl/BUILD.bazel
  tracker/rtl/br_tracker_freelist.sv
  tracker/sim/BUILD.bazel
  tracker/sim/br_tracker_freelist_tb.sv
Labels: enhancement

#254 Fix data integrity bug in bypass circular buffer implementation
  fifo/rtl/internal/br_fifo_staging_buffer.sv
Labels: bug

#255 Fix FIFO testbenches after stability assertion addition
  cdc/sim/br_cdc_fifo_flops_push_credit_tb.sv
  cdc/sim/br_cdc_fifo_flops_tb.sv
  fifo/sim/br_fifo_flops_push_credit_tb.sv
  fifo/sim/br_fifo_flops_tb.sv
Labels: bug

#259 Use === for comb asserts on delay libs when NumStages == 0
  delay/rtl/br_delay.sv
  delay/rtl/br_delay_nr.sv
  delay/rtl/br_delay_valid.sv
  delay/rtl/br_delay_valid_next.sv
  delay/rtl/br_delay_valid_next_nr.sv
Labels: bug

#258 Allow priority encoder to produce multiple results
  enc/rtl/BUILD.bazel
  enc/rtl/br_enc_priority_encoder.sv
  enc/sim/BUILD.bazel
  enc/sim/br_enc_priority_encoder_tb.sv
Labels: enhancement

#257 Support for multiple allocation ports in br_tracker_freelist
  tracker/rtl/BUILD.bazel
  tracker/rtl/br_tracker_freelist.sv
  tracker/sim/BUILD.bazel
  tracker/sim/br_tracker_freelist_tb.sv
Labels: enhancement

#268 Implement `br_flow_serializer` and `br_flow_deserializer`
  flow/rtl/BUILD.bazel
  flow/rtl/br_flow_deserializer.sv
  flow/rtl/br_flow_serializer.sv
Labels: enhancement
