Repository xlsynth/bedrock-rtl, pull requests merged in 2025-01, with the labels that each got.

#285 Use bash shell for subprocess.run in verilog_runner
  python/verilog_runner/util.py
Labels: bug

#286 Add ASSERT_KNOWN family of macros
  macros/BUILD.bazel
  macros/br_asserts.svh
  macros/br_asserts_internal.svh
  macros/br_asserts_internal_test.sv
  macros/br_asserts_test.sv
Labels: enhancement

#287 Fix elab fails at HEAD
  fifo/rtl/internal/BUILD.bazel
  fifo/sim/br_fifo_test_harness.sv
  ram/sim/br_ram_flops_1r1w_tb.sv
Labels: bug

#288 Rename REGIL to REGLI to match the actual argument order
  README.adoc
  arb/rtl/internal/br_arb_lru_internal.sv
  arb/rtl/internal/br_arb_rr_internal.sv
  cdc/rtl/internal/br_cdc_fifo_pop_flag_mgr.sv
  cdc/rtl/internal/br_cdc_fifo_push_flag_mgr.sv
  counter/rtl/br_counter.sv
  counter/rtl/br_counter_decr.sv
  counter/rtl/br_counter_incr.sv
  credit/rtl/br_credit_counter.sv
  delay/rtl/br_delay_shift_reg.sv
  fifo/rtl/internal/br_fifo_pop_ctrl.sv
  macros/br_registers.svh
  tracker/rtl/br_tracker_freelist.sv
Labels: bug

#289 Re-enable test for #148
  ram/rtl/BUILD.bazel
Labels: bug

#290 Add BR_ASSERT_FINAL macro
  macros/br_asserts.svh
  macros/br_asserts_test.sv
Labels: enhancement

#293 Fix tool pragmas in br_misc_* modules
  misc/rtl/br_misc_tieoff_one.sv
  misc/rtl/br_misc_tieoff_zero.sv
  misc/rtl/br_misc_unused.sv
Labels: enhancement

#297 Avoid x-prop from select to pop_valid when push_valid is low
  flow/rtl/br_flow_demux_select_unstable.sv
Labels: bug

#299 Bugfix in br_flow_serializer (caught by lint)
  flow/rtl/br_flow_serializer.sv
Labels: bug

#294 Counters: Add parameter for EnableReinitAnd[Incr|Decr|Change]
  counter/rtl/BUILD.bazel
  counter/rtl/br_counter.sv
  counter/rtl/br_counter_decr.sv
  counter/rtl/br_counter_incr.sv
Labels: enhancement

#295 br_flow_checks_valid_data_[intg|impl]
  credit/rtl/BUILD.bazel
  credit/rtl/br_credit_sender.sv
  fifo/rtl/internal/BUILD.bazel
  fifo/rtl/internal/br_fifo_push_ctrl_core.sv
  flow/rtl/BUILD.bazel
  flow/rtl/br_flow_demux_select.sv
  flow/rtl/br_flow_demux_select_unstable.sv
  flow/rtl/br_flow_deserializer.sv
  flow/rtl/br_flow_fork.sv
  flow/rtl/br_flow_join.sv
  flow/rtl/br_flow_mux_select.sv
  flow/rtl/br_flow_mux_select_unstable.sv
  flow/rtl/br_flow_reg_both.sv
  flow/rtl/br_flow_reg_fwd.sv
  flow/rtl/br_flow_reg_rev.sv
  flow/rtl/br_flow_serializer.sv
  flow/rtl/internal/BUILD.bazel
  flow/rtl/internal/br_flow_arb_core.sv
  flow/rtl/internal/br_flow_checks_valid_data_impl.sv
  flow/rtl/internal/br_flow_checks_valid_data_intg.sv
  flow/rtl/internal/br_flow_mux_core.sv
Labels: enhancement

#304 dont allow push_credit to assert during reset
  credit/rtl/br_credit_receiver.sv
Labels: bug

#315 Remove incorrect final assertion from br_enc_onehot2bin
  enc/rtl/br_enc_onehot2bin.sv
  tracker/rtl/br_tracker_freelist.sv
Labels: bug

#317 Make comb assertions enabled by default; update documentation
  README.adoc
  bazel/br_verilog.bzl
  macros/br_asserts.svh
  macros/br_asserts_internal.svh
Labels: documentation

#312 Remove unnecessary pop_valid fanin to push_ready in br_flow_serializer
  flow/rtl/br_flow_serializer.sv
Labels: bug

#318 Scrub all module documentation
  README.adoc
Labels: documentation

#319 Document BR_ASSERT_IN_RESET*
  README.adoc
Labels: documentation

#320 Document that BR_ASSERT_COMB builds an always_comb
  README.adoc
  macros/br_asserts.svh
Labels: documentation

#314 stall credit release until flopped reset deassert
  credit/rtl/br_credit_receiver.sv
Labels: bug

#298 Split CDC FIFO control into push/pop side
  cdc/rtl/BUILD.bazel
  cdc/rtl/br_cdc_bit_toggle.sv
  cdc/rtl/br_cdc_fifo_ctrl_1r1w.sv
  cdc/rtl/br_cdc_fifo_ctrl_1r1w_push_credit.sv
  cdc/rtl/br_cdc_fifo_ctrl_pop_1r1w.sv
  cdc/rtl/br_cdc_fifo_ctrl_push_1r1w.sv
  cdc/rtl/br_cdc_fifo_ctrl_push_1r1w_push_credit.sv
Labels: enhancement

#321 mux: create br_mux_array
  flow/rtl/br_flow_deserializer.sv
  flow/rtl/br_flow_serializer.sv
  mux/rtl/BUILD.bazel
  mux/rtl/br_mux_bin.sv
  mux/rtl/br_mux_bin_array.sv
  mux/sim/br_mux_bin_tb.sv
  ram/rtl/br_ram_flops_1r1w_tile.sv
Labels: enhancement

#323 Two-wire handshake for resetting credit sender & receiver + fix "in reset" assert macros
  cdc/rtl/br_cdc_fifo_ctrl_1r1w_push_credit.sv
  cdc/rtl/br_cdc_fifo_ctrl_push_1r1w_push_credit.sv
  cdc/rtl/br_cdc_fifo_flops_push_credit.sv
  cdc/rtl/internal/BUILD.bazel
  cdc/rtl/internal/br_cdc_fifo_push_ctrl_credit.sv
  cdc/sim/BUILD.bazel
  cdc/sim/br_cdc_fifo_flops_push_credit_tb.sv
  credit/rtl/BUILD.bazel
  credit/rtl/br_credit_counter.sv
  credit/rtl/br_credit_receiver.sv
  credit/rtl/br_credit_sender.sv
  fifo/rtl/BUILD.bazel
  fifo/rtl/br_fifo_ctrl_1r1w_push_credit.sv
  fifo/rtl/br_fifo_flops_push_credit.sv
  fifo/rtl/internal/br_fifo_push_ctrl_credit.sv
  fifo/sim/BUILD.bazel
  fifo/sim/br_fifo_flops_push_credit_tb.sv
  macros/br_asserts.svh
  macros/br_asserts_internal.svh
  macros/br_asserts_internal_test.sv
  macros/br_asserts_test.sv
Labels: bug, enhancement

#326 Remove unnecessary isunknown() calls on br_mux_bin, br_mux_onehot
  mux/rtl/br_mux_bin.sv
  mux/rtl/br_mux_onehot.sv
Labels: bug

#353 br_delay_skew / br_delay_deskew
  delay/rtl/BUILD.bazel
  delay/rtl/br_delay_deskew.sv
  delay/rtl/br_delay_skew.sv
Labels: enhancement

#350 Add ChipStack section to README
  README.adoc
Labels: documentation

#375 fix verilog runner at HEAD
  python/verilog_runner/BUILD.bazel
  python/verilog_runner/iverilog.py
  python/verilog_runner/logging_utils.py
  python/verilog_runner/util.py
  python/verilog_runner/util_test.py
  python/verilog_runner/verilog_runner.py
Labels: bug

#376 amba: fix atbytes width
  amba/rtl/br_amba_atb_funnel.sv
Labels: bug

#379 Rename `br_gate_mock.sv` and drop it from all `verilog_library` dependencies
  cdc/rtl/BUILD.bazel
  cdc/rtl/internal/BUILD.bazel
  cdc/sim/BUILD.bazel
  gate/rtl/BUILD.bazel
  gate/rtl/br_gate_mock.sv
  macros/BUILD.bazel
  mux/rtl/BUILD.bazel
  mux/sim/BUILD.bazel
  ram/rtl/BUILD.bazel
Labels: enhancement

#390 amba: reset bresp register
  amba/rtl/internal/br_amba_axi2axil_core.sv
Labels: bug

#395 Remove spurious semicolons in macros/br_asserts.svh
  macros/br_asserts.svh
Labels: bug

#396 SECDED ECC: output the encoded codeword; fix the unit test
  ecc/rtl/br_ecc_secded_decoder.sv
  ecc/rtl/br_ecc_secded_encoder.sv
  ecc/sim/br_ecc_secded_encoder_decoder_tb.sv
  python/eccgen/br_ecc_secded_decoder.sv.jinja2
  python/eccgen/br_ecc_secded_encoder.sv.jinja2
Labels: bug, enhancement

#397 Make datapath optional in `br_ram_addr_decoder` and support clock gating it when enabled
  README.adoc
  demux/rtl/br_demux_bin.sv
  ram/rtl/BUILD.bazel
  ram/rtl/br_ram_addr_decoder.sv
  ram/rtl/br_ram_flops.sv
Labels: enhancement

#400 Fix bazel tags plumbing
  bazel/verilog.bzl
Labels: bug

#404 New module: `br_delay_valid_nr`
  README.adoc
  delay/rtl/BUILD.bazel
  delay/rtl/br_delay_valid_nr.sv
Labels: enhancement

#406 Remove stale spec documents that we do not plan to maintain
  delay/spec/br_delay_comparison.adoc
  delay/spec/br_delay_nr_spec.adoc
  delay/spec/br_delay_spec.adoc
  delay/spec/br_delay_valid_next_nr_spec.adoc
  delay/spec/br_delay_valid_next_spec.adoc
  delay/spec/br_delay_valid_spec.adoc
  flow/rtl/br_flow_reg_both.sv
  flow/rtl/br_flow_reg_fwd.sv
  flow/rtl/br_flow_reg_rev.sv
  flow/spec/br_flow_reg_both_spec.adoc
  flow/spec/br_flow_reg_fwd_spec.adoc
  flow/spec/br_flow_reg_rev_spec.adoc
Labels: documentation

#402 Pass assertion parameters from br_flow_mux_core down to br_flow_arb_core
  flow/rtl/internal/br_flow_mux_core.sv
Labels: bug

#401 [br:cdc] Provide option to remove source register stage for reset active signals in CDC FIFOs
  cdc/rtl/br_cdc_fifo_ctrl_1r1w.sv
  cdc/rtl/br_cdc_fifo_ctrl_1r1w_push_credit.sv
  cdc/rtl/br_cdc_fifo_ctrl_pop_1r1w.sv
  cdc/rtl/br_cdc_fifo_ctrl_push_1r1w.sv
  cdc/rtl/br_cdc_fifo_ctrl_push_1r1w_push_credit.sv
  cdc/rtl/br_cdc_fifo_flops.sv
  cdc/rtl/br_cdc_fifo_flops_push_credit.sv
  cdc/rtl/internal/br_cdc_fifo_pop_ctrl.sv
  cdc/rtl/internal/br_cdc_fifo_pop_flag_mgr.sv
  cdc/rtl/internal/br_cdc_fifo_push_ctrl.sv
  cdc/rtl/internal/br_cdc_fifo_push_ctrl_credit.sv
  cdc/rtl/internal/br_cdc_fifo_push_flag_mgr.sv
Labels: enhancement
